### ISSUE TITLE
Measurement-based Observations on Network Traffic Dynamics

### ISSUE THREAD

**Issue by bacampbe** [intarchboard/covid19-workshop#13]
Measurement-based Observations on Network Traffic Dynamics
-  2nd to last paragraph: “This behavior is antagonistic, yet complementary, to the one observed in residential ISPs.” — I don’t understand the intent of that sentence.

- Last paragraph: “This gives another indication that the scalng of shared resources in the Internet is working resonably well enough to handle even larger changes in traffic as experience during the first nearly global lockdown of the COVID-19 pandemic. “ - Does this mean “larger changes…than experienced”?

**Comment by mirjak** [comment]
First point: my fault I copied&pasted it to the wrong position.
Second point: will fix.
