### ISSUE TITLE
Example Campus Networks:

### ISSUE THREAD

**Issue by bacampbe** [intarchboard/covid19-workshop#14]
The last sentence in the first paragraph seems redundant to the more detailed 2nd sentence.

**Comment by mirjak** [comment]
Which sentence is redundant to which...?

**Comment by bacampbe** [comment]
"The Politecnico di Torino University (Italy) deployed its in-house solution for remote teaching, which caused the outgoing traffic to grow by 2.5 times, driven by more than 600 daily online classes."
... and ...
"Further, outgoing traffic increased as well due to remote working solutions such as collaboration platforms,
VPNs and remote desktop."

I originally red the first to mean the same as the second (with more detail.), thinking of only classes as a kind of collaboration platform. But maybe those are different, and the second sentence does mention VPN, etc. Perhaps something like the following would work?

"Outgoing traffic also increased due to other remote working solutions, such as collaboration platforms, VPNs, and remote desktops."
