### ISSUE TITLE
User Behavior

### ISSUE THREAD

**Issue by bacampbe** [intarchboard/covid19-workshop#16]
“Smartphone application usage changed, with fastest growth in COVID-19, remote working, e-learning, wellness, education, remote health consultation, and social shared experienceapplications.” 

Are there words missing after COVID-19? (the growth of COVID-19, in itself, seems an odd entry for this list.)

**Comment by mirjak** [comment]
COVID-19 is actually a category; this is apps related to COVID-19 like tracking apps.

I guess we could just says "apps related to COVID-19"?

**Comment by bacampbe** [comment]
That works better. Or maybe "... related to COVID-19 tracking and information,..."?

**Comment by mirjak** [comment]
fixed by #19
