### ISSUE TITLE
Digital Divide

### ISSUE THREAD

**Issue by bacampbe** [intarchboard/covid19-workshop#17]
"One possible reason for this in the data is decisions by some ISPs, such as Comcast and Cox, that increased speeds for users on certain plans and in certain areas.” 

Is it worth noting that they increased speed for certain _lower-cost_ plans?

**Comment by mirjak** [comment]
I think that makes sense. @csperkins @jlivingood okay?

**Comment by jlivingood** [comment]
Agree - makes sense
s/on certain plans/on certain lower-cost plans

**Comment by csperkins** [comment]
Yes, that's what was discussed.
