### ISSUE TITLE
Conclusions section lacking observability conclusion

### ISSUE THREAD

**Issue by kirstyp** [intarchboard/covid19-workshop#22]
In my review of this report, I realised that there is no mention of observability in the conclusions, which seems like an oversight to be fixed, given there is a section on it in the main report.

**Comment by mirjak** [comment]
I think the first bullet point in the conclusion is meant to address observability (it just doesn't use the term):

```
Better understanding of the health of the Internet: Going forward, the critical nature that the Internet plays in our lives means that the health of the Internet needs to receive significant attention. Understanding how well networks work is not just a technical matter, it is also of crucial importance to the people and economy of the societies using it. Projects and research that monitor Internet and services performance in a broad scale and across different networks are therefore important.
```

Do need to say more? Should we just add the term observability somewhere?

**Comment by mirjak** [comment]
I created PR #25 with a minor fix to say "observability" there...

**Comment by mirjak** [comment]
PR #25 was merged.
